### ISSUE TITLE
please add the search functionality for this app

### ISSUE THREAD

**Issue by rabi-999** [ShubhamBansal1997/crud-app-vuejs-django#1]
i want to know how it works

**Comment by ShubhamBansal1997** [comment]
@rabi-999 will update by 31st March 2018 12:00 IST

**Comment by ShubhamBansal1997** [comment]
@rabi-999  sorry for getting late
[https://medium.com/@shubhambansal_89125/searchfilter-using-django-and-vue-js-215af82e12cd](https://medium.com/@shubhambansal_89125/searchfilter-using-django-and-vue-js-215af82e12cd)
Here the solution to you problem, Moreveoer refer to the commit 

[https://github.com/ShubhamBansal1997/crud-app-vuejs-django/tree/1cc519e71fed40388560f9f0b39367c57b4f0383](https://github.com/ShubhamBansal1997/crud-app-vuejs-django/tree/1cc519e71fed40388560f9f0b39367c57b4f0383)
