### ISSUE TITLE
Requirements duplicated packages

### ISSUE THREAD

**Issue by rg3915** [ShubhamBansal1997/crud-app-vuejs-django#3]
https://github.com/ShubhamBansal1997/crud-app-vuejs-django/blob/c909b66441ec2e979a4a02b2a7ed5f68380a9939/requirements.txt#L7

Your requirements contain duplicated packages.

**Comment by ShubhamBansal1997** [comment]
https://github.com/ShubhamBansal1997/crud-app-vuejs-django/commit/5f931a838285c431ef8d8acb834c517a63c359e7

check out this commit it's updated !!
Thanks for pointing out!! @rg3915
