### ISSUE TITLE
Add Pagination functionality for the table

### ISSUE THREAD

**Issue by Xednom** [ShubhamBansal1997/crud-app-vuejs-django#4]
I want to know how it works for VueJs and Django, is it based on Django or VueJs handles the pagination.

**Comment by ShubhamBansal1997** [comment]
It's simple just add a variable page and in the api call put that page parameter, and for the drf part see this link https://www.django-rest-framework.org/api-guide/pagination/

**Comment by Xednom** [comment]
I'm getting an error when using the Pagination in DRF. In the VueJs specifically. 

It says; **[Vue warn]: Error in render: "TypeError: status is null"
TypeError: "status is null"**

Currently I have a select tag and the options in it has the v-for directive for looping the data from a certain model.

in the **HTML**
`<select class="form-control" v-model="newJobRequest.status_of_the_job_request" required >
                        <option v-for="status in statusOfTheJobRequests">[[status.type_of_status]]</option>
                      </select>`

in the **JS**
`getStatusOfJobRequest: function() {
      this.loading = true;
      this.$http.get(`/api/v1/status-of-the-job-request/`)
          .then((response) => {
            this.statusOfTheJobRequests = response.data;
            this.loading = false;
          })
          .catch((err) => {
            this.loading = false;
            console.log(err);
          })
    }`

**Comment by ShubhamBansal1997** [comment]
Hey, for personal queries contact me over skype - username - shubhambansal27
