### ISSUE TITLE
How to add rich text for content body and to let only admin write and post article? (Like in WordPress)

### ISSUE THREAD

**Issue by crazycodewriter** [ShubhamBansal1997/crud-app-vuejs-django#5]
Hi @ShubhamBansal1997 
You wrote a great tutorial.
I searched a lot and found only this tutorial on Medium. But there is no any info about the rich text for blog content body. You might notice how for example in WordPress you can add different subheadings, ul s and li s and other types for content body. And it can do only admin. How can these things be implemented in this code?

**Comment by ShubhamBansal1997** [comment]
Hey Let's connect over skype to discuss this improvement, username - shubhambansal27
